### ISSUE TITLE
Require glob or path at Clap level

### ISSUE THREAD

**Issue by palfrey** [hawkins/watchdog#14]
It fails later on if neither are set, but can be caught at the arg parsing level with [`Arg::required_unless_one`](https://docs.rs/clap/2.33.0/clap/struct.Arg.html#method.required_unless_one) which would be slightly nicer than a panic. Otherwise, a good tool, thanks.

**Comment by hawkins** [comment]
Nice catch - I'm not very familiar with Clap, so I wasn't aware of that feature. Thanks for both using the tool and reporting to help me improve it! :smile:

**Comment by hawkins** [comment]
Done in v0.2.6 . Thank you very much! 🎉 https://github.com/hawkins/watchdog/releases/tag/v0.2.6
